import { freezePureData } from '../../../../content/chapterAuthoring.js';
import {
  audioSfx,
  circle,
  dialogueStart,
  flagSet,
  hagridLayoutBounds,
  noCondition,
  owlLayoutBounds,
  roomSize,
  setPiecePlay,
  travel,
  uiOpen,
  walkBand,
  when,
} from '../authoring.js';

export const bedroomRoom = freezePureData({
  id: 'ch1.bedroom',
  size: roomSize,
  background: {
    layers: ['rooms/ch1/bedroom/sky', 'rooms/ch1/bedroom/base'],
    fit: 'cover',
    focalPoint: { x: 0.5, y: 0.5 },
    keyLight: 'right',
    variants: {},
  },
  walkBand,
  spawns: {
    'bedroom.start': { x: 500, y: 610, facing: 'right' },
    'bedroom.letter': { x: 760, y: 610, facing: 'left' },
  },
  exits: [],
  occupants: [
    { npc: 'npc.violet', x: 500, y: 610, facing: 'right', pose: 'idle', when: noCondition },
    {
      npc: 'npc.owlPost',
      x: 1060,
      y: 210,
      facing: 'left',
      pose: 'perch',
      when: when({ noFlags: ['ch1.owlTapped'] }),
      render: {
        offsetY: 80,
        scale: 1.08,
        layoutBounds: owlLayoutBounds,
        lookAt: {
          target: 'npc.violet',
          rangeX: 360,
          rangeY: 300,
          offsetY: -170,
        },
      },
    },
    { npc: 'npc.guide', x: 250, y: 610, facing: 'right', pose: 'idle', when: when({ allFlags: ['ch1.letterRead'] }), render: { layoutBounds: hagridLayoutBounds } },
  ],
  hotspots: [
    {
      id: 'bedroom.owl',
      kind: 'action',
      hitArea: circle(1060, 210, 70),
      approach: { x: 950, y: 605, facing: 'right' },
      when: when({ noFlags: ['ch1.owlTapped'] }),
      presentation: { icon: 'owl', glow: 'objective' },
      repeat: 'once',
      requiredSpell: null,
      onInteract: [audioSfx('sfx/ch1/owlTap'), flagSet('ch1.owlTapped'), setPiecePlay('sp.letter')],
    },
    {
      id: 'bedroom.letter',
      kind: 'inspect',
      hitArea: circle(650, 350, 160),
      approach: { x: 760, y: 610, facing: 'left' },
      when: when({ allFlags: ['ch1.owlTapped'], noFlags: ['ch1.letterRead'] }),
      presentation: { icon: 'letter', glow: 'objective' },
      repeat: 'until-condition',
      requiredSpell: null,
      onInteract: [flagSet('ch1.letterOpened'), setPiecePlay('sp.letterOpen'), uiOpen('letter-reading')],
    },
    {
      id: 'bedroom.guide',
      kind: 'talk',
      hitArea: circle(250, 455, 95),
      approach: { x: 360, y: 610, facing: 'left' },
      when: when({ allFlags: ['ch1.letterRead'], noFlags: ['ch1.guideMet'] }),
      presentation: { icon: 'talk', glow: 'objective' },
      repeat: 'until-condition',
      requiredSpell: null,
      onInteract: [dialogueStart('ch1.guide.arrival')],
    },
    {
      id: 'bedroom.exit',
      kind: 'action',
      hitArea: circle(250, 455, 150),
      approach: null,
      when: when({ allFlags: ['ch1.guideMet'] }),
      presentation: { icon: 'door', glow: 'objective' },
      repeat: 'once',
      requiredSpell: null,
      onInteract: [travel('ch1.leaky', 'leaky.entry')],
    },
  ],
  ambientSetPieces: [],
}, 'Chapter One bedroom room draft');
