function profile({
  kind,
  appearances,
  clips,
  expressions,
  actions,
  surfaces,
  sockets = [],
  props = [],
}) {
  return Object.freeze({
    kind,
    appearances: Object.freeze(appearances),
    clips: Object.freeze(clips),
    expressions: Object.freeze(expressions),
    actions: Object.freeze(actions),
    surfaces: Object.freeze(surfaces),
    sockets: Object.freeze(sockets),
    props: Object.freeze(props),
    lightSides: Object.freeze(['left', 'right']),
    supportsReducedMotion: true,
  });
}

const HUMAN_BASE = Object.freeze({
  clips: ['idle', 'walking', 'speaking', 'jump-for-joy', 'giggle', 'tumble', 'recovery'],
  expressions: ['neutral', 'blink', 'talk-a', 'talk-b'],
  surfaces: ['world', 'portrait'],
  sockets: [
    'neck',
    'shoulderLeft', 'shoulderRight',
    'elbowLeft', 'elbowRight',
    'wristLeft', 'wristRight',
    'handLeft', 'handRight',
    'hipLeft', 'hipRight',
    'kneeLeft', 'kneeRight',
    'ankleLeft', 'ankleRight',
    'footLeft', 'footRight',
  ],
});

export const CURRENT_CHARACTER_ANIMATION_REQUIREMENTS = Object.freeze({
  'puppet.violet': profile({
    kind: 'human',
    appearances: ['casual', 'robes'],
    clips: [...HUMAN_BASE.clips, 'wand-hold', 'wand-test', 'wand-receive', 'cast', 'robe-present'],
    expressions: [...HUMAN_BASE.expressions, 'wonder', 'proud', 'curious'],
    actions: [
      'inspect', 'wrong-wand-one', 'wrong-wand-two', 'chosen-wand',
      'receive-wand', 'admire-robes', 'broom-wonder',
    ],
    surfaces: [...HUMAN_BASE.surfaces, 'title', 'robe-picker'],
    sockets: [...HUMAN_BASE.sockets, 'wandGrip', 'wandTip', 'sortingHat'],
    props: ['wand', 'robe-trim'],
  }),
  'puppet.guide': profile({
    kind: 'human',
    appearances: ['default'],
    clips: [...HUMAN_BASE.clips, 'beckon', 'map-handoff', 'ticket-handoff', 'brick-tap'],
    expressions: [...HUMAN_BASE.expressions, 'warm-smile'],
    actions: ['depart-bedroom', 'depart-leaky', 'present-map', 'present-ticket', 'open-wall'],
    surfaces: HUMAN_BASE.surfaces,
    sockets: [...HUMAN_BASE.sockets, 'mapHand', 'ticketHand', 'brickTapHand'],
    props: ['map', 'ticket'],
  }),
  'puppet.wandmaker': profile({
    kind: 'human',
    appearances: ['default'],
    clips: [...HUMAN_BASE.clips, 'assess', 'present-wand'],
    expressions: [...HUMAN_BASE.expressions, 'curious', 'surprised-amusement', 'encouraging-reset'],
    actions: ['welcome', 'wrong-wand-one', 'wrong-wand-two', 'chosen-wand'],
    surfaces: HUMAN_BASE.surfaces,
    sockets: [...HUMAN_BASE.sockets, 'wandHand'],
    props: ['wand', 'measuring-tape'],
  }),
  'puppet.tailor': profile({
    kind: 'human',
    appearances: ['default'],
    clips: [...HUMAN_BASE.clips, 'measure', 'fit', 'present-color'],
    expressions: [...HUMAN_BASE.expressions, 'approval'],
    actions: ['welcome', 'measure-violet', 'present-robes', 'approve-choice'],
    surfaces: HUMAN_BASE.surfaces,
    sockets: [...HUMAN_BASE.sockets, 'measuringHand'],
    props: ['measuring-tape', 'fabric'],
  }),
  'puppet.menagerieKeeper': profile({
    kind: 'human',
    appearances: ['default'],
    clips: [...HUMAN_BASE.clips, 'present-pets', 'ask-name', 'celebrate-friend'],
    expressions: [...HUMAN_BASE.expressions, 'proud'],
    actions: ['welcome', 'confirm-pet', 'ask-name', 'new-friend'],
    surfaces: HUMAN_BASE.surfaces,
    sockets: [...HUMAN_BASE.sockets, 'presentingHand'],
    props: ['pet-carrier'],
  }),
  'portrait.narrator': profile({
    kind: 'portrait',
    appearances: ['default'],
    clips: ['idle', 'speaking'],
    expressions: ['neutral', 'blink', 'talk-a', 'talk-b', 'warm'],
    actions: ['narrate'],
    surfaces: ['portrait', 'chapter-preview'],
    sockets: ['mouth', 'eyeLeft', 'eyeRight'],
  }),
  'puppet.owlPost': profile({
    kind: 'creature',
    appearances: ['post'],
    clips: ['idle', 'perch', 'takeoff', 'delivery', 'flight', 'release', 'settle'],
    expressions: ['neutral', 'blink', 'beak-open'],
    actions: ['window-perch', 'tap-response', 'deliver-letter', 'release-letter'],
    surfaces: ['world', 'title', 'set-piece'],
    sockets: ['eyeLeft', 'eyeRight', 'beak', 'talonLeft', 'talonRight', 'letterCarry', 'letterRelease'],
    props: ['letter'],
  }),
  'puppet.pet.cat': profile({
    kind: 'creature',
    appearances: ['pet'],
    clips: ['idle', 'pet-follow', 'curious', 'paw', 'celebrate'],
    expressions: ['neutral', 'blink'],
    actions: ['selection', 'follow', 'objective-look', 'secret-hint', 'mirror', 'finale'],
    surfaces: ['world', 'portrait', 'pet-picker'],
    sockets: ['eyeLeft', 'eyeRight', 'nose', 'pawLeft', 'pawRight', 'footContact'],
  }),
  'puppet.pet.owl': profile({
    kind: 'creature',
    appearances: ['pet'],
    clips: ['idle', 'perch', 'pet-follow', 'wing-flick', 'curious', 'celebrate'],
    expressions: ['neutral', 'blink', 'beak-open'],
    actions: ['selection', 'follow', 'objective-look', 'secret-hint', 'mirror', 'finale'],
    surfaces: ['world', 'portrait', 'pet-picker'],
    sockets: ['eyeLeft', 'eyeRight', 'beak', 'talonLeft', 'talonRight', 'footContact'],
  }),
  'puppet.pet.toad': profile({
    kind: 'creature',
    appearances: ['pet'],
    clips: ['idle', 'pet-follow', 'curious', 'croak', 'celebrate'],
    expressions: ['neutral', 'blink'],
    actions: ['selection', 'follow', 'objective-look', 'mirror', 'finale'],
    surfaces: ['world', 'portrait', 'pet-picker'],
    sockets: ['eyeLeft', 'eyeRight', 'mouth', 'footContact'],
  }),
});

export function characterAnimationRequirement(id) {
  return CURRENT_CHARACTER_ANIMATION_REQUIREMENTS[id] ?? null;
}
