const WORD_PATTERN = /[\p{L}\p{N}]+(?:['’][\p{L}\p{N}]+)*/gu;

export const coreVocabulary = Object.freeze([
  'a',
  'again',
  'amber',
  'back',
  'board',
  'bricks',
  'broom',
  'cat',
  'cards',
  'choose',
  'color',
  'colour',
  'come',
  'continue',
  'coral',
  'dear',
  'emerald',
  'explore',
  'fast',
  'find',
  'first',
  'flying',
  'follow',
  'for',
  'fresh',
  'friend',
  'go',
  'hear',
  'lavender',
  'later',
  'letter',
  "let's",
  'look',
  'lovely',
  'magic',
  'map',
  'me',
  'midnight',
  'my',
  'name',
  'new',
  'next',
  'one',
  'oops',
  'open',
  'owl',
  'own',
  'pet',
  'pick',
  'place',
  'play',
  'reload',
  'return',
  'rose',
  'robes',
  'ruby',
  'silver',
  'sky',
  'so',
  'spells',
  'start',
  'tap',
  'that',
  'toad',
  'the',
  "train's",
  'ticket',
  'this',
  'to',
  'train',
  'try',
  'use',
  'wand',
  'way',
  'witch',
  'with',
  'wow',
  'yes',
  'your',
]);

export const properNouns = Object.freeze([
  'biscuit',
  'dumbledore',
  'gold',
  'hagrid',
  'hogwarts',
  'morgana',
  'pip',
  'purple',
  'quill',
  'star',
  'teal',
  'violet',
  "violet's",
]);

const allowedWords = new Set([...coreVocabulary, ...properNouns]);

export function captionWords(caption) {
  if (typeof caption !== 'string') return [];
  return (caption.match(WORD_PATTERN) ?? []).map((word) => word.replaceAll('’', "'").toLocaleLowerCase('en-US'));
}

export function isSupportedCaption(caption, maximumWords = 3) {
  const words = captionWords(caption);
  return words.length > 0 && words.length <= maximumWords && words.every((word) => allowedWords.has(word));
}
