import { chapter1DialogueDefinitions } from './dialogues.js';
import { chapter1QuestDefinition } from './quests.js';

export const chapter1AssetKeys = [
    'rooms/ch1/bedroom/base',
    'rooms/ch1/bedroom/sky',
    'rooms/ch1/leaky/base',
    'rooms/ch1/courtyard/base',
    'rooms/ch1/diagon/day',
    'rooms/ch1/diagon/dusk',
    'rooms/ch1/ollivanders/base',
    'rooms/ch1/malkins/base',
    'rooms/ch1/menagerie/base',
    'maps/ch1/diagon',
    'chapterCards/ch1/platform',
    'cards/morgana/portrait',
    'cards/dumbledore/portrait',
    'music/ch1/violetTheme',
    'music/ch1/diagonAlley',
    'music/ch1/chapterTriumph',
    'ambience/ch1/bedroom',
    'ambience/ch1/leaky',
    'ambience/ch1/diagon',
    'ambience/ch1/shop',
    'sfx/ch1/owlTap',
    'sfx/ch1/owlFlap',
    'sfx/ch1/paperSlide',
    'sfx/ch1/sealCrack',
    'sfx/ch1/wallRumble',
    'sfx/ch1/brickClack',
    'sfx/ch1/wandPaperWhirl',
    'sfx/ch1/vaseShatter',
    'sfx/ch1/wandChosen',
    'sfx/ch1/coin',
    'sfx/ch1/ticket',
    'sfx/ch1/chapterTurn',
    'sfx/ch1/petCat',
    'sfx/ch1/petOwl',
    'sfx/ch1/petToad',
    'voice/ch1/card/morgana',
    'voice/ch1/card/dumbledore',
    ...chapter1DialogueDefinitions.flatMap((dialogue) =>
      Object.values(dialogue.nodes)
        .filter((node) => node.type === 'line')
        .map((node) => node.voice),
    ),
    ...Object.values(chapter1QuestDefinition.steps).map((step) => step.objective.voice),
    'voice/ch1/recap/openLetter',
    'voice/ch1/recap/followGuide',
    // recap/useMap is shared by the live useMap objective above.
    'voice/ch1/recap/chooseRobes',
    'voice/ch1/recap/choosePet',
    'voice/ch1/recap/returnToGuide',
];
