import { storybookChecklist } from '../../../content/visualVerification.js';
import {
  dialogueStart,
  flagSet,
  musicCue,
  sfxCue,
  travel,
  violetActionCue,
} from './authoring.js';

export const chapter1SetPieceDefinitions = {
  'sp.letter': {
    id: 'sp.letter',
    tier: 'T2',
    duration: 2.25,
    clock: 'world',
    blocksInput: true,
    particleBudget: 'standard',
    assets: ['rooms/ch1/bedroom/base', 'rooms/ch1/bedroom/sky', 'sfx/ch1/owlTap', 'sfx/ch1/owlFlap', 'sfx/ch1/paperSlide', 'sfx/ch1/sealCrack'],
    fallback: 'fallback.letterCrossfade',
    reducedMotion: 'reduced.letterDeliveryFade',
    params: { specification: 'SP-01' },
    timeline: { tracks: [sfxCue(0.25, 'sfx/ch1/owlFlap'), sfxCue(0.95, 'sfx/ch1/paperSlide')] },
    verification: { keyframes: [0, 1.16, 2.25], checklist: storybookChecklist('Violet is legible on the envelope.', 'Control returns as soon as the letter reaches the canonical resting-envelope pose.', 'No painting edge is exposed.') },
    onComplete: [],
  },
  'sp.letterOpen': {
    id: 'sp.letterOpen',
    tier: 'T2',
    duration: 4.6,
    clock: 'world',
    blocksInput: true,
    particleBudget: 'standard',
    assets: ['sfx/ch1/sealCrack', 'sfx/ch1/paperSlide'],
    fallback: 'fallback.letterCrossfade',
    reducedMotion: 'reduced.letterOpenFade',
    params: { specification: 'SP-01', variant: 'open-invitation' },
    timeline: { tracks: [sfxCue(0.2, 'sfx/ch1/sealCrack'), sfxCue(1.05, 'sfx/ch1/paperSlide')] },
    verification: {
      keyframes: [0, 0.35, 0.9, 1.55, 2.25, 3.1, 4.6],
      checklist: storybookChecklist('Opening frame zero matches the delivered envelope exactly.', 'The closed envelope stays above Violet’s protected head region.', 'The irregular owl seal visibly cracks before restrained wax pieces part.', 'The flap, paper rise, and two folds each have a distinct readable beat.', 'No opaque material layers ghost through one another.', 'No intermediate frame becomes a large blank rectangle.', 'The invitation settles into the exact reading-surface position.'),
    },
    onComplete: [],
  },
  'reduced.letterDeliveryFade': {
    id: 'reduced.letterDeliveryFade',
    tier: 'T1',
    duration: 1.9,
    clock: 'world',
    blocksInput: true,
    particleBudget: 'reduced',
    assets: ['sfx/ch1/owlFlap', 'sfx/ch1/paperSlide'],
    fallback: null,
    reducedMotion: null,
    params: { specification: 'SP-01', variant: 'reduced-delivery' },
    timeline: { tracks: [sfxCue(0.15, 'sfx/ch1/owlFlap'), sfxCue(0.4, 'sfx/ch1/paperSlide')] },
    verification: { keyframes: [0, 0.5, 1.9], checklist: storybookChecklist('The owl and envelope crossfade without rapid travel.', 'The delivered letter reaches its normal resting place.') },
    onComplete: [],
  },
  'reduced.letterOpenFade': {
    id: 'reduced.letterOpenFade',
    tier: 'T1',
    duration: 1.35,
    clock: 'world',
    blocksInput: true,
    particleBudget: 'reduced',
    assets: ['sfx/ch1/sealCrack', 'sfx/ch1/paperSlide'],
    fallback: null,
    reducedMotion: null,
    params: { specification: 'SP-01', variant: 'reduced-open' },
    timeline: { tracks: [sfxCue(0.2, 'sfx/ch1/sealCrack'), sfxCue(0.45, 'sfx/ch1/paperSlide')] },
    verification: { keyframes: [0, 0.5, 1.3], checklist: storybookChecklist('The canonical sealed envelope cuts cleanly to the fully readable invitation without overlapping material.', 'The reading actions appear without a static input lock.') },
    onComplete: [],
  },
  'sp.brickWall': {
    id: 'sp.brickWall',
    tier: 'T3',
    duration: 2.6,
    clock: 'world',
    blocksInput: true,
    particleBudget: 'standard',
    assets: ['rooms/ch1/courtyard/base', 'rooms/ch1/diagon/day', 'sfx/ch1/wallRumble', 'sfx/ch1/brickClack'],
    fallback: 'fallback.doubleHingedWall',
    reducedMotion: 'reduced.wallCrossfade',
    params: { specification: 'SP-02', columns: 10, rows: 8 },
    timeline: { tracks: [sfxCue(0, 'sfx/ch1/wallRumble'), sfxCue(0.45, 'sfx/ch1/brickClack')] },
    verification: { keyframes: [0, 0.6, 1, 1.4, 1.65, 1.8, 2.05, 2.2, 2.6], checklist: storybookChecklist('The courtyard remains unchanged outside the intact wall before the first bricks move.', 'Each moving cell reads as one opaque brick opening from the center outward, with Diagon Alley visible only through the gaps.', 'The same stable-scale street reveal expands across the outgoing courtyard and cast during the burst, with no second transition afterward.') },
    onComplete: [flagSet('ch1.wallOpened'), travel('ch1.diagonStreet', 'street.west', 'none')],
  },
  'sp.wandChaos1': {
    id: 'sp.wandChaos1',
    tier: 'T2',
    duration: 2.2,
    clock: 'world',
    blocksInput: true,
    particleBudget: 'standard',
    assets: ['sfx/ch1/wandPaperWhirl'],
    fallback: 'fallback.papersOnly',
    reducedMotion: 'reduced.papersShort',
    params: { specification: 'SP-03', variant: 'papers' },
    timeline: { tracks: [
      violetActionCue('wrong-wand-one', {
        expression: 'curious',
        temporaryProp: 'prop.ch1.wand1',
      }),
      sfxCue(0, 'sfx/ch1/wandPaperWhirl'),
    ] },
    verification: { keyframes: [0, 0.8, 1.5, 2.2], checklist: storybookChecklist('Every paper settles before control returns.') },
    onComplete: [flagSet('ch1.wandTry1'), dialogueStart('ch1.wandmaker.wrong1')],
  },
  'sp.wandChaos2': {
    id: 'sp.wandChaos2',
    tier: 'T2',
    duration: 2.6,
    clock: 'world',
    blocksInput: true,
    particleBudget: 'standard',
    assets: ['sfx/ch1/wandPaperWhirl', 'sfx/ch1/vaseShatter'],
    fallback: 'fallback.papersAndWobble',
    reducedMotion: 'reduced.vaseSwap',
    params: { specification: 'SP-03', variant: 'vase' },
    timeline: { tracks: [
      violetActionCue('wrong-wand-two', {
        expression: 'curious',
        temporaryProp: 'prop.ch1.wand2',
      }),
      sfxCue(0, 'sfx/ch1/wandPaperWhirl'),
      sfxCue(1.05, 'sfx/ch1/vaseShatter'),
    ] },
    verification: { keyframes: [0, 0.8, 1.6, 2.6], checklist: storybookChecklist('Vase shards stay inside the room.', 'Every prop settles before control returns.') },
    onComplete: [flagSet('ch1.wandTry2'), dialogueStart('ch1.wandmaker.wrong2')],
  },
  'sp.wandChosen': {
    id: 'sp.wandChosen',
    tier: 'T2',
    duration: 3,
    clock: 'world',
    blocksInput: true,
    particleBudget: 'standard',
    assets: ['sfx/ch1/wandChosen'],
    fallback: 'fallback.goldenWash',
    reducedMotion: 'reduced.goldenFade',
    params: { specification: 'SP-03', variant: 'golden-choice', crescendoAt: 1.65 },
    timeline: { tracks: [
      violetActionCue('chosen-wand', {
        expression: 'wonder',
        temporaryProp: 'prop.ch1.wandChosen',
      }),
      sfxCue(0, 'sfx/ch1/wandChosen'),
    ] },
    verification: { keyframes: [0, 1, 2, 3], checklist: storybookChecklist('The golden wash does not clip to white.', 'The chosen wand remains visible.') },
    onComplete: [
      { type: 'character.set', field: 'wandId', value: 'violet-first-wand' },
      flagSet('ch1.wandChosen'),
      { type: 'yearbook.capture', moment: 'ch1.wandChosen' },
      dialogueStart('ch1.wandmaker.chosen'),
    ],
  },
  'sp.chapterCard': {
    id: 'sp.chapterCard',
    tier: 'T1',
    duration: 4,
    clock: 'world',
    blocksInput: true,
    particleBudget: 'standard',
    assets: ['chapterCards/ch1/platform', 'sfx/ch1/chapterTurn'],
    fallback: 'fallback.staticPage',
    reducedMotion: 'reduced.staticPage',
    params: { specification: 'chapter-card' },
    timeline: { tracks: [sfxCue(0, 'sfx/ch1/chapterTurn'), musicCue(0.2, 'music/ch1/chapterTriumph')] },
    verification: { keyframes: [0, 1, 4], checklist: storybookChecklist('The chapter title is legible.', 'The page transition reveals no blank frame.') },
    onComplete: [dialogueStart('ch1.narrator.chapterEnd')],
  },
};
